using FluentAssertions;
using Majik.Core.Abilities;
using Majik.Core.CardData;
using Majik.Core.CardData.Factories;
using Majik.Core.Cards;
using Majik.Core.Cards.Types;
using Majik.Core.Costs;
using Majik.Core.Effects;
using Majik.Core.Players;
using Majik.Core.ValueObjects;
using Majik.Core.Zones;
using Xunit;

namespace Majik.Core.Tests.CardData.Factories;

/// <summary>
/// Tests for <see cref="StalkingStonesFactory"/> (Urza's Saga colorless
/// creature-land).
/// Land:
///   "{T}: Add {C}.
///    {6}: This land becomes a 3/3 Elemental artifact creature that's still
///    a land. (This effect lasts indefinitely.)"
///   (Oracle verified against Scryfall 2026-05-29.)
///
/// Same colorless-manland animate shape as <see cref="MishrasFactoryFactory"/>:
/// a {T}: Add {C} mana ability (from the embedded JSON definition) and a {6}:
/// animate activated ability. Distinct from the Worldwake manland cycle and
/// from Ghitu Encampment in one crucial way: the animation is <b>indefinite</b>,
/// not "until end of turn" (CR 611.2b — a continuous effect generated by a
/// resolved activated ability with no stated duration lasts indefinitely).
/// Stalking Stones therefore uses its own effect classes whose
/// <see cref="ContinuousEffect.ExpiresAtEndOfTurn"/> is <c>false</c>, so the
/// 3/3 Elemental artifact body survives cleanup
/// (<see cref="ContinuousEffectsService.ExpireEndOfTurn"/>).
/// </summary>
public class StalkingStonesFactoryTests
{
    private readonly Player _alice = new("Alice", 20);

    // -----------------------------------------------------------------------
    // Identity + dispatch
    // -----------------------------------------------------------------------

    [Fact]
    public void StalkingStones_Identity()
    {
        var land = StalkingStonesFactory.Create(_alice);

        land.Name.Should().Be("Stalking Stones");
        land.HasType(CardType.Land).Should().BeTrue();
        land.HasType(CardType.Creature).Should().BeFalse(
            "printed shape is plain Land until activated");
        land.HasSupertype(CardSupertype.Basic).Should().BeFalse(
            "Stalking Stones is a nonbasic land");
        land.Subtypes.Should().BeEmpty();
        land.Supertypes.Should().BeEmpty();
        land.Owner.Should().BeSameAs(_alice);
        land.Controller.Should().BeSameAs(_alice);
    }

    [Fact]
    public void NamedCardFactory_Dispatches_StalkingStones()
    {
        var card = NamedCardFactory.Create("Stalking Stones", _alice);

        card.Should().BeOfType<Land>();
        card.Name.Should().Be("Stalking Stones");
        card.HasType(CardType.Land).Should().BeTrue();

        card.Abilities.OfType<ManaAbility>().Should().HaveCount(1,
            "{T}: Add {C}");
        card.Abilities
            .Where(a => a.GetType() == typeof(ActivatedAbility))
            .Should().HaveCount(1, "the {6} animate ability");
    }

    // -----------------------------------------------------------------------
    // {T}: Add {C}
    // -----------------------------------------------------------------------

    [Fact]
    public void StalkingStones_TapForC_ProducesColorless()
    {
        var land = StalkingStonesFactory.Create(_alice);
        var c = land.Abilities.OfType<ManaAbility>().Single();

        c.CanActivate().Should().BeTrue();
        var produced = c.Activate();

        // {C} parses to one generic pip in the engine's ManaCost model
        // (ManaCost.Parse maps 'C' -> generic++), matching the colorless-land
        // convention used by Wasteland / Strip Mine / Crawling Barrens tests.
        produced.Generic.Should().Be(1);
        produced.White.Should().Be(0);
        produced.Blue.Should().Be(0);
        produced.Black.Should().Be(0);
        produced.Red.Should().Be(0);
        produced.Green.Should().Be(0);
        land.IsTapped.Should().BeTrue();
    }

    // -----------------------------------------------------------------------
    // Animate ability ({6})
    // -----------------------------------------------------------------------

    [Fact]
    public void StalkingStones_AnimateAbility_HasPrintedManaCost6()
    {
        var land = StalkingStonesFactory.Create(_alice);

        var animate = AnimateOf(land);
        var manaCost = animate.Costs.OfType<ManaCostCost>().Should()
            .ContainSingle("the animate cost is one ManaCostCost ({6})").Subject;
        manaCost.Cost.Generic.Should().Be(6, "{6} is six generic mana");
        animate.IsSorcerySpeed.Should().BeFalse(
            "animate is instant-speed per oracle");
    }

    [Fact]
    public void StalkingStones_Animate_AppliesLayer4OnCompute()
    {
        var effects = new ContinuousEffectsService();
        var land = StalkingStonesFactory.Create(_alice, effects);
        _alice.Zones.Battlefield.AddCard(land);
        land.SetZone(ZoneType.Battlefield);

        AnimateOf(land).Resolve();

        var chars = effects.Compute((Permanent)land);
        chars.Types.Should().Contain(CardType.Land,
            "printed Land type stays through Layer 4 — \"that's still a land\"");
        chars.Types.Should().Contain(CardType.Creature,
            "Layer 4 adds Creature");
        chars.Types.Should().Contain(CardType.Artifact,
            "the animated body is an artifact creature");
        chars.Subtypes.Should().Contain(CardSubtype.Elemental,
            "Elemental subtype added");
    }

    [Fact]
    public void StalkingStones_Animate_RegistersLayer4AndLayer7b_Indefinite()
    {
        var effects = new ContinuousEffectsService();
        var land = StalkingStonesFactory.Create(_alice, effects);
        land.SetZone(ZoneType.Battlefield);

        AnimateOf(land).Resolve();

        var animateEffect = GetRegisteredEffects(effects)
            .OfType<StalkingStonesAnimateEffect>()
            .SingleOrDefault(e => ReferenceEquals(e.Target, land));
        animateEffect.Should().NotBeNull();
        animateEffect!.Layer.Should().Be(Layer.Type);
        animateEffect.ExpiresAtEndOfTurn.Should().BeFalse(
            "CR 611.2b — the animation lasts indefinitely, not until EOT");
        animateEffect.Subtypes.Should().Contain(CardSubtype.Elemental);
        animateEffect.ExtraTypes.Should().Contain(CardType.Artifact);

        var ptEffect = GetRegisteredEffects(effects)
            .OfType<StalkingStonesBecomesPTEffect>()
            .SingleOrDefault(e => e.NewPower == 3 && e.NewToughness == 3);
        ptEffect.Should().NotBeNull();
        ptEffect!.Layer.Should().Be(Layer.PT_SetBase);
        ptEffect.ExpiresAtEndOfTurn.Should().BeFalse(
            "the 3/3 body lasts indefinitely too");
    }

    [Fact]
    public void StalkingStones_Animate_SurvivesEndOfTurn()
    {
        var effects = new ContinuousEffectsService();
        var land = StalkingStonesFactory.Create(_alice, effects);
        land.SetZone(ZoneType.Battlefield);

        AnimateOf(land).Resolve();

        // CR 514.2 — "until end of turn" effects end during cleanup. Stalking
        // Stones' animation has no stated duration (CR 611.2b) so it must
        // SURVIVE cleanup, unlike every "until end of turn" manland.
        effects.ExpireEndOfTurn();

        GetRegisteredEffects(effects)
            .OfType<StalkingStonesAnimateEffect>()
            .Where(e => ReferenceEquals(e.Target, land))
            .Should().HaveCount(1, "indefinite animation persists past cleanup");

        var chars = effects.Compute((Permanent)land);
        chars.Types.Should().Contain(CardType.Land);
        chars.Types.Should().Contain(CardType.Creature,
            "still a 3/3 Elemental artifact creature after EOT");
        chars.Types.Should().Contain(CardType.Artifact);
        chars.Subtypes.Should().Contain(CardSubtype.Elemental);
    }

    [Fact]
    public void StalkingStones_Animate_NoEffectsService_NoOp_ShapeRemainsLand()
    {
        var land = StalkingStonesFactory.Create(_alice);
        land.SetZone(ZoneType.Battlefield);

        var resolve = () => AnimateOf(land).Resolve();
        resolve.Should().NotThrow();
        land.HasType(CardType.Creature).Should().BeFalse();
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static ActivatedAbility AnimateOf(Land land) =>
        land.Abilities
            .Where(a => a.GetType() == typeof(ActivatedAbility))
            .Cast<ActivatedAbility>()
            .Single();

    private static IEnumerable<ContinuousEffect> GetRegisteredEffects(
        ContinuousEffectsService svc)
    {
        var field = typeof(ContinuousEffectsService).GetField(
            "_effects",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        var list = (System.Collections.IEnumerable)field!.GetValue(svc)!;
        foreach (var e in list) yield return (ContinuousEffect)e;
    }
}
