using Majik.Core.Abilities;
using Majik.Core.CardData.Definitions;
using Majik.Core.Cards;
using Majik.Core.Cards.Types;
using Majik.Core.Costs;
using Majik.Core.Effects;
using Majik.Core.Players;

namespace Majik.Core.CardData.Factories;

/// <summary>
/// Named-card factory for Stalking Stones (Urza's Saga colorless creature-land).
/// Land.
///
/// Oracle text (verified against Scryfall 2026-05-29):
///   "{T}: Add {C}.
///    {6}: This land becomes a 3/3 Elemental artifact creature that's still
///    a land. (This effect lasts indefinitely.)"
///
/// Shares the colorless-manland animate shape used by
/// <see cref="MishrasFactoryFactory"/>: a single {T}: Add {C} mana ability
/// (CR 605.1) and a {6} animate <see cref="ActivatedAbility"/> whose
/// resolution turns the land into a 3/3 Elemental artifact creature that is
/// still a land (CR 613.1c — "It's still a land": the added Creature +
/// Artifact types and the Elemental subtype layer on top of the printed Land).
///
/// ## What is unique to Stalking Stones vs the rest of the cycle
/// - <b>Indefinite duration.</b> Unlike Mishra's Factory / Ghitu Encampment /
///   the Worldwake cycle (all "until end of turn"), Stalking Stones'
///   animation lasts <i>indefinitely</i> (CR 611.2b — a continuous effect
///   generated by the resolution of an activated ability that has no stated
///   duration lasts indefinitely). It therefore does NOT reuse the shared
///   <see cref="ManlandCycleAnimateEffect"/> / <see cref="ManlandCycleBecomesPTEffect"/>
///   (those hardcode <see cref="ContinuousEffect.ExpiresAtEndOfTurn"/> = true).
///   Instead it registers its own <see cref="StalkingStonesAnimateEffect"/>
///   (Layer 4) + <see cref="StalkingStonesBecomesPTEffect"/> (Layer 7b), both
///   leaving the base <see cref="ContinuousEffect.ExpiresAtEndOfTurn"/> = false
///   so <see cref="ContinuousEffectsService.ExpireEndOfTurn"/> (CR 514.2
///   cleanup) does NOT lift the animation.
/// - <b>{6} colourless activation cost</b> — no tap rider, six generic mana.
/// - <b>Artifact creature body</b> — the animate effect adds the Artifact type
///   in addition to Creature (same posture as Mishra's Factory's
///   "Assembly-Worker artifact creature").
///
/// The base shape (plain nonbasic Land + the {T}: Add {C} mana ability) is
/// materialised from the embedded JSON definition (<c>stalking-stones.json</c>)
/// via <see cref="CardDefinitionLoader.FromEmbeddedResource"/> +
/// <see cref="CardDefinitionFactory.Build"/>; the animate ability is layered
/// on here because the JSON <c>AbilityDefinition</c> schema does not express
/// it yet (same posture as <see cref="GhituEncampmentFactory"/>).
///
/// ## v1 posture (shared with the manland cycle)
/// - <b>Combat math through Compute</b> — same gap as every other manland:
///   <see cref="ContinuousEffectsService.Compute(Permanent)"/> seeds a plain
///   <see cref="PermanentCharacteristics"/> row for a Land runtime instance,
///   so the 3/3 body is recorded for inspection but doesn't surface for
///   combat resolution yet. The Creature / Artifact types and Elemental
///   subtype DO apply via Compute.
/// </summary>
[CardName("Stalking Stones")]
public static class StalkingStonesFactory
{
    public const string CardName = "Stalking Stones";
    public const string Slug = "stalking-stones";
    public const int AnimatedPower = 3;
    public const int AnimatedToughness = 3;

    /// <summary>
    /// Construct Stalking Stones with no <see cref="ContinuousEffectsService"/>
    /// wired. The {T}: Add {C} mana ability (from JSON) + the animate ability
    /// are attached so the card surface is complete; the layer effects are
    /// not registered. This is the overload <see cref="NamedCardFactory"/>
    /// dispatches to.
    /// </summary>
    public static Land Create(Player owner) =>
        Create(owner, effects: null);

    /// <summary>
    /// Construct Stalking Stones with an optional continuous-effects service.
    /// </summary>
    /// <param name="owner">Card owner / initial controller.</param>
    /// <param name="effects">Continuous-effects service for Layer 4 + Layer
    /// 7b registration of the animate ability. May be null — the ability
    /// still resolves but no continuous effects are recorded.</param>
    public static Land Create(Player owner, ContinuousEffectsService? effects)
    {
        ArgumentNullException.ThrowIfNull(owner);

        // Base shape from the embedded JSON definition (name, Land type,
        // {T}: Add {C} mana ability). The animate ability is layered on
        // below — it is not expressible in the current JSON
        // AbilityDefinition schema.
        var definition = CardDefinitionLoader.FromEmbeddedResource(Slug);
        var land = (Land)CardDefinitionFactory.Build(definition, owner);

        // ----------------------------------------------------------------
        // {6}: This land becomes a 3/3 Elemental artifact creature that's
        // still a land. (This effect lasts indefinitely.)
        //
        // CR 602 — ordinary activated ability (uses the stack). Resolution
        // registers Layer 4 + Layer 7b continuous effects with NO stated
        // duration, so they persist past cleanup (CR 611.2b).
        // ----------------------------------------------------------------
        var animateEffect = new Effect(
            $"{CardName}: becomes {AnimatedPower}/{AnimatedToughness} Elemental artifact creature indefinitely (still a land)",
            () =>
            {
                if (effects == null) return; // no service wired — shape-only path

                // Layer 4 — add Creature + Artifact types + Elemental
                // subtype. Printed Land type stays ("that's still a land",
                // CR 613.1c).
                effects.Register(new StalkingStonesAnimateEffect(land));

                // Layer 7b — set base P/T 3/3.
                effects.Register(new StalkingStonesBecomesPTEffect(
                    land, AnimatedPower, AnimatedToughness));
            });

        land.AddAbility(new ActivatedAbility(
            source: land,
            controller: owner,
            costs: new ICost[] { new ManaCostCost("{6}") },
            effects: new IEffect[] { animateEffect }));

        return land;
    }
}

/// <summary>
/// Stalking Stones — activated-ability resolution: Layer 4 type-adding
/// effect. Adds <see cref="CardType.Creature"/> + <see cref="CardType.Artifact"/>
/// and the <see cref="CardSubtype.Elemental"/> subtype to the land's
/// effective characteristics. Printed <see cref="CardType.Land"/> stays
/// (CR 613.1c — "that's still a land").
///
/// <b>Indefinite duration</b> — leaves the base
/// <see cref="ContinuousEffect.ExpiresAtEndOfTurn"/> = false (CR 611.2b), so
/// <see cref="ContinuousEffectsService.ExpireEndOfTurn"/> does NOT lift it.
/// This is the one behavioural difference from
/// <see cref="ManlandCycleAnimateEffect"/>, which is why Stalking Stones gets
/// its own effect class rather than reusing the shared cycle primitive.
/// </summary>
public sealed class StalkingStonesAnimateEffect : ContinuousEffect
{
    private readonly Permanent _target;

    public StalkingStonesAnimateEffect(Permanent target)
    {
        _target = target ?? throw new ArgumentNullException(nameof(target));
    }

    /// <summary>The permanent being animated.</summary>
    public Permanent Target => _target;

    /// <summary>Subtypes granted by the animation (Elemental).</summary>
    public IReadOnlyList<CardSubtype> Subtypes { get; } =
        new[] { CardSubtype.Elemental };

    /// <summary>Extra card types granted on top of Creature (Artifact).</summary>
    public IReadOnlyList<CardType> ExtraTypes { get; } =
        new[] { CardType.Artifact };

    public override Layer Layer => Layer.Type;

    public override Permanent? Source => _target;

    public override bool IsActive() =>
        _target.Zone == Majik.Core.Zones.ZoneType.Battlefield;

    // No override of ExpiresAtEndOfTurn → base default false (CR 611.2b:
    // indefinite duration).

    public override bool AppliesTo(Creature creature) => AppliesTo((Permanent)creature);

    public override bool AppliesTo(Permanent permanent) =>
        ReferenceEquals(permanent, _target);

    public override void Apply(CreatureCharacteristics chars) =>
        Apply((PermanentCharacteristics)chars);

    public override void Apply(PermanentCharacteristics chars)
    {
        chars.Types.Add(CardType.Creature);
        chars.Types.Add(CardType.Artifact);
        chars.Subtypes.Add(CardSubtype.Elemental);
    }
}

/// <summary>
/// Stalking Stones — activated-ability resolution: Layer 7b set-base P/T
/// effect recording the 3/3 the land turns into (CR 613.7b). Same "Land
/// runtime instance" shim posture as <see cref="ManlandCycleBecomesPTEffect"/>:
/// <see cref="ContinuousEffectsService.Compute(Permanent)"/> seeds a plain
/// <see cref="PermanentCharacteristics"/> row with no P/T fields, so the
/// effect is registered for layer-system correctness and exposes
/// <see cref="NewPower"/> / <see cref="NewToughness"/> for inspection.
///
/// <b>Indefinite duration</b> — base
/// <see cref="ContinuousEffect.ExpiresAtEndOfTurn"/> = false (CR 611.2b).
/// </summary>
public sealed class StalkingStonesBecomesPTEffect : ContinuousEffect
{
    private readonly Permanent _target;

    /// <summary>The base power the target becomes (CR 613.7b).</summary>
    public int NewPower { get; }

    /// <summary>The base toughness the target becomes (CR 613.7b).</summary>
    public int NewToughness { get; }

    public StalkingStonesBecomesPTEffect(Permanent target, int power, int toughness)
    {
        _target = target ?? throw new ArgumentNullException(nameof(target));
        NewPower = power;
        NewToughness = toughness;
    }

    public override Layer Layer => Layer.PT_SetBase;

    public override Permanent? Source => _target;

    public override bool IsActive() =>
        _target.Zone == Majik.Core.Zones.ZoneType.Battlefield;

    public override bool AppliesTo(Creature creature) => ReferenceEquals(creature, _target);

    public override bool AppliesTo(Permanent permanent) => ReferenceEquals(permanent, _target);

    public override void Apply(CreatureCharacteristics chars)
    {
        chars.Power = NewPower;
        chars.Toughness = NewToughness;
    }

    // No Apply(PermanentCharacteristics) override: the base default
    // dispatches to Apply(CreatureCharacteristics) when the working set is a
    // creature row. ContinuousEffectsService.Compute upgrades an animated
    // Land to a creature row (CR 613.1c) on a Layer-4 Creature grant, so this
    // set-base lands and the animated body surfaces through combat math.
}
